# -*- coding: utf-8 -*-
"""posicaoFalsa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fjVHPZBJFrkDhO7ZHGc6UF3VDH9FYCut
"""

import numpy as np

def f(x):
  f = x**2 - 9*x + 3
  return f

a = 0
b = 1
tol = 1e-4

x = (a*f(b)-b*f(a))/(f(b)-f(a))

k = 0

while abs(f(x)) > tol:
  x = (a*f(b)-b*f(a))/(f(b)-f(a))
  print(k,a,x,b,f(a),f(x),f(b))

  if f(a)*f(x) < 0:
    a = a
    b = x

  elif f(x)*f(b) > 0:
    a = x
    b = b
  

  k+=1


print('O resultado é ', x)